* Resources
https://tecosaur.github.io/emacs-config/config.html
https://dotdoom.rgoswami.me/config
* Doom Keybinds
Set the leader to spacemacs
#+begin_src emacs-lisp
(setq doom-localleader-key ",")
#+end_src
* Doom
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+begin_src emacs-lisp
(setq doom-theme 'modus-vivendi)

#+end_src

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type `relative)
#+end_src
* Evil-mode
#+begin_src emacs-lisp
(setq evil-shift-round nil)
#+end_src
* Which Key
Set the whick key opening delay to  0.5 seconds
#+begin_src emacs-lisp
(setq which-key-idle-delay 0.5)
#+end_src

replace evil- in which-key entries to make em easier to read
#+begin_src emacs-lisp
(setq which-key-allow-multiple-replacements t)
(after! which-key
  (pushnew!
   which-key-replacement-alist
   '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . "◂\\1"))
   '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . "◃\\1"))
   ))

#+end_src
* Org Mode
Set the directory
#+begin_src emacs-lisp

(add-hook 'org-mode-hook 'turn-on-org-cdlatex)
(add-hook 'LaTeX-mode-hook 'turn-on-cdlatex)

(defun enable-word-processor-minor-modes ()
  (setq line-spacing 0.15)
  ;;(pixel-scroll-precision-mode)
  (smartparens-mode)
  (visual-line-mode))
;;  (add-hook 'window-size-change-functions 'org-image-resize)
(add-hook 'text-mode-hook 'enable-word-processor-minor-modes)
;;(add-hook 'org-mode-hook 'org-appear-mode)
(add-hook 'org-mode-hook 'org-roam-db-autosync-enable)
(add-hook 'org-mode-hook 'org-latex-preview-auto-mode)
(after! org
  (setq org-directory "~/notes/org-mode/")
  (setq org-roam-directory "~/notes/org-mode/")
  (setq org-habit-show-habits-only-for-today nil)
  (setq org-agenda-files (directory-files-recursively "~/notes/org-mode/" "\\.org$"))
  (setq org-pretty-entities t)
  (setq org-hide-emphasis-markers t)
  (setq org-startup-folded 'content)
  (setq org-ellipsis " ")) ;; folding symbol
#+end_src
** Org Writeroom
Setting the variable fonts
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Iosevka Nerd Font Mono" :size 18)
      doom-variable-pitch-font (font-spec :family "Vollkorn"))
#+end_src

#+begin_src emacs-lisp
(after! org
  (setq +zen-text-scale 1)
  (setq writeroom-width 1.8)
  )
(add-hook 'org-mode-hook 'writeroom-mode)
#+end_src
** Run buffers in org-mode by default:
#+begin_src emacs-lisp
(setq-default major-mode 'org-mode)
#+end_src
** Org Keybinds

I want the following keybinds to be added that i've noticed
The *insert* maps
The *text* maps
Comment lines
ctrl c ctrl c
copy and clipboard.
display org roam tags in node search
Other stuff- daemon mode,
smartparens equivalency (default +smartparens under doom config is NOT all you need, bind sp-sexp-up to tab)
** Org Appear
#+begin_src emacs-lisp
(after! org
  (setq org-appear-autolinks t)
  (setq org-appear-autoentities t)
  (setq org-appear-autosubmarkers t)
  (setq org-appear-autokeywords t)
  (setq org-appear-inside-latex t)
  )

;; It's cool to have appear only work in insert mode, gonna leave in automatic for now
;; (setq org-appear-trigger 'manual)
;; (add-hook 'org-mode-hook (lambda ()
;;                           (add-hook 'evil-insert-state-entry-hook
;;                                     #'org-appear-manual-start
;;                                     nil
;;                                     t)
;;                           (add-hook 'evil-insert-state-exit-hook
;;                                     #'org-appear-manual-stop
;;                                     nil
;;                                     t)))
#+end_src
** Org Download
#+begin_src emacs-lisp
(after! org-download
  (setq org-download-method 'directory)
  (setq org-download-image-dir (concat org-directory ".attach/" ))
  (setq org-download-link-format "[[file:%s]]\n"
        org-download-abbreviate-filename-function #'file-relative-name)
  (setq org-download-link-format-function #'org-download-link-format-function-default)
)
#+end_src
Add an advice to supress org-get-id call on org-download-clipboard
#+begin_src emacs-lisp
(after! org
(advice-remove 'org-download-clipboard 'org-id-get-create))
#+end_src
** Org-roam
Fix that annoying sqlitep nil error:
#+begin_src emacs-lisp
(defun patch/emacsql-close (connection &rest args)
  "Prevent calling emacsql-close if connection handle is nil."
  (when (oref connection handle)
    t))

(advice-add 'emacsql-close :before-while #'patch/emacsql-close)
#+end_src
** Org-indent
#+begin_src emacs-lisp
(after! org
  (setq org-indent-indentation-per-level 4))
#+end_src
* Transparency
#+begin_src  emacs-lisp
(set-frame-parameter nil 'alpha-background 0.6)
#+end_src
* LSP
Set up ccls
#+begin_src emacs-lisp
(after! ccls
  (setq ccls-initialization-options '(:index (:comments 2) :completion (:detailedLabel t)))
  (set-lsp-priority! 'ccls 2)) ; optional as ccls is the default in Doom
#+end_src
lens update is very slow
#+begin_src emacs-lisp
  (setq lsp-lens-enable nil)
#+end_src
* Projectile
#+begin_src emacs-lisp
  (setq projectile-cache-file (concat doom-cache-dir "projectile.cache")
        projectile-enable-caching (not noninteractive)
        projectile-indexing-method (if IS-WINDOWS 'native 'alien)
        projectile-known-projects-file (concat doom-cache-dir "projectile.projects")
        projectile-require-project-root nil
        projectile-globally-ignored-files '(".DS_Store" "Icon
" "TAGS")
        projectile-globally-ignored-file-suffixes '(".elc" ".pyc" ".o")
        projectile-ignored-projects '("~/" "/tmp"))
#+end_src
* Ultra scroll mode
#+begin_src emacs-lisp

  (setq scroll-conservatively 3 ; or whatever value you prefer, since v0.4
        scroll-margin 0)        ; important: scroll-margin>0 not yet supported
(ultra-scroll-mode 1)

#+end_src
